name: PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

env:
  DOCKER_IMAGE_NAME: ghcr.io/your-ko/link-validator

jobs:
  PR:
    name: PR
    runs-on: ubuntu-22.04
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v6.0.0
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build metadata
        id: meta
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Go Vet
        shell: bash
        run: |
          go vet ./cmd/... ./internal/... ./pkg/...

      - name: Go Test
        shell: bash
        env:
          CGO_ENABLED: 1
        run: |
          go test -race ./cmd/... ./internal/... ./pkg/...

      - name: Build Check image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERSION="PR"
            BUILD_DATE=${{ steps.meta.outputs.BUILD_DATE }}
            GIT_COMMIT=${{ steps.meta.outputs.GIT_COMMIT }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.meta.outputs.GIT_COMMIT }},${{ env.DOCKER_IMAGE_NAME }}:PR
          provenance: false
          push: false

      - name: Link validation
        uses: your-ko/link-validator@1.3.0
        with:
          log-level: 'info'
          pat: ${{ secrets.GITHUB_TOKEN }}
